webapp/config/routes.rb
Rails.application.routes.draw do
  root 'guests#index'

  devise_for :users, skip: [:sessions]

  resources :guests, only: [:index, :create]

  resources :machines do
    member do
      post 'start'
      post 'pause'
      post 'resume'
      post 'stop'
      post 'force_stop'
      post 'restart'
      post 'force_restart'

      post 'mount_iso'

      get 'state'
    end

    resources :disks do
      member do
        post 'resize'
        post 'snapshot'
      end
    end
  end

  get '/progress/:id', to: 'progress#progress', as: 'progress'
  get '/machine_progress/:id', to: 'progress#machine', as: 'machine_progress'
end

webapp/app/views/layouts/_doorbell.html.slim
- app_key = Rails.configuration.x.doorbell.app_key
- app_id = Rails.configuration.x.doorbell.app_id

- if app_key and app_id
  javascript:
    window.doorbellOptions = {
      #{raw doorbell_signature}
      appKey: '#{app_key}'
    };

  script#doorbellScript type='text/javascript' src="https://doorbell.io/button/#{app_id}" async='true'

webapp/app/views/layouts/_newsletter.html.slim
.newsletter.text-center
  .description
    p
      | This is the hosted alpha of VirtKick,
      br.hidden-xs
      | a free & open source alternative to OpenStack and SolusVM.

    p
      | Check out the #{link_to 'static prototype', 'https://demo.virtkick.io/'}
      |  to get familiar with all planned features.


    h3 Sign up for standalone beta!

  form.form-inline action='https://virtkick.us8.list-manage.com/subscribe/post?u=b74a227fdbddc9f590a62114e&amp;id=08823d8a7b' method='post' role='form'

    .input-group
      input.newsletter-email.form-control.input name='EMAIL' placeholder='e-mail address' type='text'
      span.input-group-btn
        input.btn.btn-primary name='subscribe' type='submit' value='go!'

  p.result data-success='Thanks! Please check your e-mail.'

webapp/app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset='utf-8'
    meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'
    title
      = @title || 'Alpha: VirtKick, 1-Click Cloud Management'
    meta name='description' content='A prototype of VirtKick, a user-oriented cloud management center.'
    meta name='viewport' content='width=device-width'
    link rel='shortcut icon' href='/favicon.ico'
    = stylesheet_link_tag 'application', media: 'all'
    = requirejs_include_tag 'application'
    = csrf_meta_tags
  body
    .mobile-newsletter.hidden-md.hidden-lg
      .container
        = render partial: 'layouts/newsletter'

    .container.main
      .row.header
        .menu.col-md-3.hidden-xs.hidden-sm
          = link_to machines_path do
            = image_tag 'logo/virtkick-logo-pixelart-64.png'

        .header.col-md-6
          - if @header
            h1
              - if @icon
                span class="oi oi-#{@icon}"
              = @header
          - else
            = yield :header

        .action.col-md-3
          = yield :action

      .row
        .col-md-3.side-menu-wrapper
          nav.navbar.navbar-default.side-menu role="navigation"
            .navbar-header.hidden-md.hidden-lg
              button.navbar-toggle data-target="#navbar-collapsable" data-toggle="collapse" type="button"
                span.sr-only Toggle navigation
                span.icon-bar
                span.icon-bar
                span.icon-bar
              a.navbar-brand href='/'
                = image_tag 'logo/virtkick-logo-pixelart-48.png', class: 'pix'
                |  virt
                span.kick kick
            #navbar-collapsable.collapse.navbar-collapse
              ul.nav.navbar-nav
                - if user_signed_in?
                  = navbar_item machines_path do
                    span.oi.oi-monitor
                    | Machines
                - else
                  = navbar_item new_user_session_path do
                    span.fa.fa-sign-in
                    | Sign in
                = navbar_item 'https://www.virtkick.io', class: 'home' do
                  span.fa.fa-rocket
                  | VirtKick.io
          .dropdown
            button.btn.btn-primary
              span.caret
              
          .desktop-newsletter.hidden-xs.hidden-sm.text-center
            = render partial: 'layouts/newsletter'


        .col-md-9
          - if notice
            .alert.alert-info = notice
          - if alert
            .alert.alert-warning = alert

          = yield


    = javascript_include_tag 'application'
    = render partial: 'layouts/doorbell'
    = yield :scripts

    /[if lte IE 8]
      #old-browser
        javascript:
          document.getElementById('page').style.display = 'none';
        div
          | You are using an outdated browser.<br/>
            Please <a href="http://browsehappy.com/">upgrade your browser</a> to access this website.

webapp/app/views/layouts/raw.html.slim
doctype html
html
  head
    meta charset='utf-8'
    meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'
    title
      = @title || 'Alpha: VirtKick, 1-Click Cloud'
    meta name='description' content='A prototype of VirtKick, a user-oriented cloud management center.'
    meta name='viewport' content='width=device-width'
    link rel='shortcut icon' href='/favicon.ico'
    = stylesheet_link_tag 'application', media: 'all'
    //= javascript_include_tag 'snippets'
    = requirejs_include_tag 'application'
    = csrf_meta_tags
  body
    = yield

    /[if lte IE 8]
      #old-browser
        javascript:
          document.getElementById('page').style.display = 'none';
        div
          | You are using an outdated browser.<br/>
            Please <a href="http://browsehappy.com/">upgrade your browser</a> to access this website.